apiVersion: v1
kind: Service
metadata:
  name: jerney-backend
  namespace: journey-ns
  labels:
    app: journey-backend
spec:
  type: ClusterIP
  selector:
    app: journey-backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP